//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Ed_Services.DBServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ABCEndServiceLib.DB")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEnrolledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StduentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEnrolled {
            get {
                return this.DateEnrolledField;
            }
            set {
                if ((this.DateEnrolledField.Equals(value) != true)) {
                    this.DateEnrolledField = value;
                    this.RaisePropertyChanged("DateEnrolled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StduentName {
            get {
                return this.StduentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StduentNameField, value) != true)) {
                    this.StduentNameField = value;
                    this.RaisePropertyChanged("StduentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIDField, value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/ABCEndServiceLib.DB")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseIDField, value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enrollment", Namespace="http://schemas.datacontract.org/2004/07/ABCEndServiceLib.DB")]
    [System.SerializableAttribute()]
    public partial class Enrollment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseIDField, value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIDField, value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBServiceRef.IDBService")]
    public interface IDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InsertAStudent", ReplyAction="http://tempuri.org/IDBService/InsertAStudentResponse")]
        int InsertAStudent(ABC_Ed_Services.DBServiceRef.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InsertAStudent", ReplyAction="http://tempuri.org/IDBService/InsertAStudentResponse")]
        System.Threading.Tasks.Task<int> InsertAStudentAsync(ABC_Ed_Services.DBServiceRef.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InsertACourse", ReplyAction="http://tempuri.org/IDBService/InsertACourseResponse")]
        int InsertACourse(ABC_Ed_Services.DBServiceRef.Course c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InsertACourse", ReplyAction="http://tempuri.org/IDBService/InsertACourseResponse")]
        System.Threading.Tasks.Task<int> InsertACourseAsync(ABC_Ed_Services.DBServiceRef.Course c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InsertEnrolment", ReplyAction="http://tempuri.org/IDBService/InsertEnrolmentResponse")]
        int InsertEnrolment(ABC_Ed_Services.DBServiceRef.Enrollment e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/InsertEnrolment", ReplyAction="http://tempuri.org/IDBService/InsertEnrolmentResponse")]
        System.Threading.Tasks.Task<int> InsertEnrolmentAsync(ABC_Ed_Services.DBServiceRef.Enrollment e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAllStudents", ReplyAction="http://tempuri.org/IDBService/GetAllStudentsResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student> GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAllStudents", ReplyAction="http://tempuri.org/IDBService/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student>> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAllCourses", ReplyAction="http://tempuri.org/IDBService/GetAllCoursesResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course> GetAllCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAllCourses", ReplyAction="http://tempuri.org/IDBService/GetAllCoursesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course>> GetAllCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetEnrollmentsForStudent", ReplyAction="http://tempuri.org/IDBService/GetEnrollmentsForStudentResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course> GetEnrollmentsForStudent(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetEnrollmentsForStudent", ReplyAction="http://tempuri.org/IDBService/GetEnrollmentsForStudentResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course>> GetEnrollmentsForStudentAsync(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/getStudentsEnrolledInCourse", ReplyAction="http://tempuri.org/IDBService/getStudentsEnrolledInCourseResponse")]
        System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student> getStudentsEnrolledInCourse(string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/getStudentsEnrolledInCourse", ReplyAction="http://tempuri.org/IDBService/getStudentsEnrolledInCourseResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student>> getStudentsEnrolledInCourseAsync(string courseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServiceChannel : ABC_Ed_Services.DBServiceRef.IDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<ABC_Ed_Services.DBServiceRef.IDBService>, ABC_Ed_Services.DBServiceRef.IDBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertAStudent(ABC_Ed_Services.DBServiceRef.Student s) {
            return base.Channel.InsertAStudent(s);
        }
        
        public System.Threading.Tasks.Task<int> InsertAStudentAsync(ABC_Ed_Services.DBServiceRef.Student s) {
            return base.Channel.InsertAStudentAsync(s);
        }
        
        public int InsertACourse(ABC_Ed_Services.DBServiceRef.Course c) {
            return base.Channel.InsertACourse(c);
        }
        
        public System.Threading.Tasks.Task<int> InsertACourseAsync(ABC_Ed_Services.DBServiceRef.Course c) {
            return base.Channel.InsertACourseAsync(c);
        }
        
        public int InsertEnrolment(ABC_Ed_Services.DBServiceRef.Enrollment e) {
            return base.Channel.InsertEnrolment(e);
        }
        
        public System.Threading.Tasks.Task<int> InsertEnrolmentAsync(ABC_Ed_Services.DBServiceRef.Enrollment e) {
            return base.Channel.InsertEnrolmentAsync(e);
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student> GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student>> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course> GetAllCourses() {
            return base.Channel.GetAllCourses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course>> GetAllCoursesAsync() {
            return base.Channel.GetAllCoursesAsync();
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course> GetEnrollmentsForStudent(string studentId) {
            return base.Channel.GetEnrollmentsForStudent(studentId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Course>> GetEnrollmentsForStudentAsync(string studentId) {
            return base.Channel.GetEnrollmentsForStudentAsync(studentId);
        }
        
        public System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student> getStudentsEnrolledInCourse(string courseId) {
            return base.Channel.getStudentsEnrolledInCourse(courseId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ABC_Ed_Services.DBServiceRef.Student>> getStudentsEnrolledInCourseAsync(string courseId) {
            return base.Channel.getStudentsEnrolledInCourseAsync(courseId);
        }
    }
}
